name: CodeceptJS Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run E2E tests
      run: npx codeceptjs run --reporter mochawesome

    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output
        path: output/
        retention-days: 30